// Runs against the collected snapshot in GitHub's installed Chrome.
const {chromium}=require('/tmp/dashboard-browser-check/node_modules/playwright');
const assert=require('assert'),fs=require('fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:960}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/#home');
 await page.locator('.competitor-row').first().waitFor();
 assert.equal(await page.locator('.portfolio-product').count(),20);
 assert.equal(await page.locator('#homeProductName').innerText(),'Hadlima');
 assert((await page.locator('#homeCompetitors').innerText()).includes('Humira'));
 await page.locator('[data-portfolio="ospomyv"]').click();
 assert((await page.locator('#homeCompetitors').innerText()).includes('Prolia'));
 assert(!(await page.locator('#homeCompetitors').innerText()).includes('Xbryk'));
 await page.locator('[data-portfolio="pyzchiva"]').click();
 await page.locator('#homeNews article').first().waitFor();
 await page.locator('#homeRegulatory').click();
 assert.equal(await page.locator('#molecule').inputValue(),'ustekinumab');
 assert((await page.locator('#matrix thead').innerText()).includes('Pyzchiva'));
 assert.equal(await page.locator('#regulatoryPage h1').innerText(),'Regulatory information');
 const regulatoryColor=await page.locator('#reloadBtn').evaluate(n=>getComputedStyle(n).color);
 await page.locator('.section-tabs a[href="#home"]').click();
 assert.equal(await page.locator('#homeProductName').innerText(),'Pyzchiva');
 await page.locator('#homeAllNews').click();
 await page.locator('.news-card').first().waitFor();
 assert.equal(await page.locator('#newsRange').inputValue(),'all');
 assert(await page.locator('#newsMolecules input[value="ustekinumab"]').isChecked());
 assert.equal(await page.locator('#newsRefresh').evaluate(n=>getComputedStyle(n).color),regulatoryColor);
 await page.locator('.section-tabs a[href="#home"]').click();
 await page.locator('[data-portfolio="sb38"]').click();
 assert((await page.locator('#homeCompetitors').innerText()).includes('수집 범위'));
 assert(await page.locator('#homeRegulatory').isHidden());
 await page.locator('[data-portfolio="hadlima"]').click();
 await page.evaluate(()=>window.scrollTo(0,0));
 fs.mkdirSync('/tmp/dashboard-shots',{recursive:true});
 const desktop=await page.screenshot({path:'/tmp/dashboard-shots/home-desktop.jpg',type:'jpeg',quality:45});
 console.log('DESKTOP_IMAGE '+desktop.toString('base64'));
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 const mobile=await page.screenshot({path:'/tmp/dashboard-shots/home-mobile.jpg',type:'jpeg',quality:45});
 console.log('MOBILE_IMAGE '+mobile.toString('base64'));
 await page.setViewportSize({width:1280,height:960});
 await page.locator('.section-tabs a[href="#news"]').click();
 await page.locator('#newsClear').click();
 await page.locator('#newsRange').selectOption('90');
 await page.locator('.news-card').first().waitFor();
 const initial=await page.locator('.news-card').count();assert(initial>0);
 await page.locator('#newsMolecules input[value="ustekinumab"]').check();
 assert(await page.locator('.news-card').count()>0);
 for(const card of await page.locator('.news-card').all())assert((await card.innerText()).includes('ustekinumab'));
 await page.locator('#newsRange').selectOption('custom');
 await page.locator('#newsFrom').fill('2026-09-08');await page.locator('#newsTo').fill('2026-01-01');
 assert((await page.locator('#newsResultCount').innerText()).includes('시작일'));
 await page.locator('#newsRange').selectOption('90');await page.locator('#newsClear').click();
 fs.mkdirSync('/tmp/dashboard-shots',{recursive:true});
 await page.screenshot({path:'/tmp/dashboard-shots/news-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 await page.screenshot({path:'/tmp/dashboard-shots/news-mobile.png',fullPage:true});
 await page.locator('a[href="#regulatory"]').click();
 await page.locator('#molecule').selectOption('ustekinumab');
 await page.getByRole('button',{name:'전체 선택',exact:true}).click();
 await page.getByText('FDA letter 당시',{exact:false}).first().waitFor();
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Browser verified: source-backed news, molecule/date filters, mobile width, approval-letter rendering.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
